name=BLE UART MX
version=1.1
author=Oleg Volkov
maintainer=Oleg Volkov
sentence=Multipurpose dual role BLE to serial bridge
paragraph=Configurable communication device with USB or serial interface able to create multiple connections or accept connections from other central device
category=Communication
url=https://github.com/olegv142/esp32-ble-uart-mx
architectures=esp32
depends=
